name: hava
version: 0.1.0.0
github: "laban211/hava"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2021 Author Daniel Tabacskó"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hava#readme>

dependencies:
  - base >= 4.7 && < 5
  - split
  - cassava
  - csv
  - bytestring
  - vector
  - text
  - stringsearch
  - utf8-string
  - containers
  - time
  - HUnit

library:
  source-dirs: src

executables:
  hava-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hava

tests:
  hava-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hava
