name: Haskell CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.8"
          stack-version: "latest"

      - name: "Set up HLint"
        uses: haskell-actions/hlint-setup@v2

      - name: "Run HLint"
        uses: haskell-actions/hlint-run@v2
        with:
          path: .
          fail-on: warning

      - name: Download Ormolu binary
        run: |
          curl -L https://github.com/tweag/ormolu/releases/download/0.6.0.1/ormolu-Linux.zip -o ormolu.zip
          unzip ormolu.zip
          chmod +x ormolu
          sudo mv ormolu /usr/local/bin/
          ormolu --version

      - name: Check formatting with ormolu
        run: |
          ormolu --mode check $(find . -name '*.hs')

      - name: Build and test with Stack
        run: |
          stack setup
          stack build
          stack test
