name: Haskell CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: "9.4.8"
          stack-version: "latest"

      - name: Install ormolu and hlint
        run: |
          stack install ormolu
          stack install hlint

      - name: Check formatting with ormolu
        run: |
          ormolu --mode check $(find . -name '*.hs')

      - name: Run linting with hlint
        run: |
          hlint .

      - name: Build and test with Stack
        run: |
          stack setup
          stack build
          stack test
